---

- name:   Spooler management example
  hosts: all
  tasks:

    - name: Ensure that the spooler service is started
      ansible.windows.win_service:
        name: spooler
        state: started

    - name: Ensure that the Web-server service is installed 
      ansible.windows.win_feature:
        name: Web-server
        state: present

...